kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myuser2-read-pod
subjects:
- kind: ServiceAccount
  name: myuser2
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: read-pod
  apiGroup: "rbac.authorization.k8s.io"
