apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs-fg
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-rs
  template:
    metadata:
      labels:
        app: myapp-rs
        env: dev
    spec:
      containers:
      - name: myapp
        image: ghcr.io/c1t1d0s7/go-myweb:alpine
        ports:
        - containerPort: 8080
